#!/bin/bash
# ──────────────────────────────────────────────
# cleanup.sh — Tear down all local testing resources
# ──────────────────────────────────────────────
# Stops containers, deletes Postgres volume (full DB reset),
# removes the test Docker image, and removes Lambda zip artifacts.
#
# Run from project root:
#   bash test/cleanup.sh
#
# After cleanup you can start fresh:
#   bash test/test_full_chain.sh
# ──────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[cleanup]${NC} $1"; }
warn() { echo -e "${YELLOW}[cleanup]${NC} $1"; }

# ─── Stop containers and delete volumes ───────────────────────────────────
log "Stopping containers and deleting Postgres volume..."
if docker compose ps -q 2>/dev/null | grep -q .; then
    docker compose down -v
    log "Containers stopped, volumes deleted ✓"
else
    docker compose down -v 2>/dev/null || true
    warn "No running containers found (already stopped)"
fi

# ─── Remove test Docker image ─────────────────────────────────────────────
if docker image inspect marsquant-export-test > /dev/null 2>&1; then
    log "Removing Docker image marsquant-export-test..."
    docker rmi marsquant-export-test
    log "Image removed ✓"
else
    warn "Image marsquant-export-test not found (already removed)"
fi

# ─── Remove Lambda zip artifacts (generated by Terraform) ─────────────────
log "Removing generated Lambda zip files..."
REMOVED=0
for f in lambda/orchestrator.zip lambda/verify.zip lambda/drop_partition.zip; do
    if [ -f "$f" ]; then
        rm -f "$f"
        REMOVED=$((REMOVED + 1))
    fi
done
[ "$REMOVED" -gt 0 ] && log "Removed ${REMOVED} zip file(s) ✓" || warn "No zip files found"

echo ""
log "════════════════════════════════════════"
log "  Cleanup complete ✓"
log "  Postgres volume deleted → fresh DB on next 'docker compose up -d'"
log "════════════════════════════════════════"
